project: shared/showroom

data:
#  raw_data_path: '../input/ieee-fraud-detection'
#  features_data_path: '../input/features-v0'

  raw_data_path: '../input'
  features_data_path: ''

  prediction_data_path: ''
  sample_submission_path: '../input/sample_submission.csv'